// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acc_wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccWalletForUpdate = `-- name: GetAccWalletForUpdate :one
SELECT wallet_id, amount, created_at, updated_at
FROM acc_wallet
WHERE wallet_id = $1
FOR UPDATE
`

func (q *Queries) GetAccWalletForUpdate(ctx context.Context, walletID int32) (AccWallet, error) {
	row := q.db.QueryRow(ctx, getAccWalletForUpdate, walletID)
	var i AccWallet
	err := row.Scan(
		&i.WalletID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccWalletBalance = `-- name: UpdateAccWalletBalance :one
UPDATE acc_wallet
SET amount = amount + $1, updated_at = now()
WHERE wallet_id = $2
AND amount + $1 >= 0
RETURNING wallet_id, amount, created_at, updated_at
`

type UpdateAccWalletBalanceParams struct {
	Amount   pgtype.Numeric `db:"amount" json:"amount"`
	WalletID int32          `db:"wallet_id" json:"wallet_id"`
}

func (q *Queries) UpdateAccWalletBalance(ctx context.Context, arg UpdateAccWalletBalanceParams) (AccWallet, error) {
	row := q.db.QueryRow(ctx, updateAccWalletBalance, arg.Amount, arg.WalletID)
	var i AccWallet
	err := row.Scan(
		&i.WalletID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
