// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccWallet struct {
	WalletID  int32            `db:"wallet_id" json:"wallet_id"`
	Amount    pgtype.Numeric   `db:"amount" json:"amount"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UtxoWallet struct {
	TxID      uuid.UUID        `db:"tx_id" json:"tx_id"`
	WalletID  int32            `db:"wallet_id" json:"wallet_id"`
	Amount    pgtype.Numeric   `db:"amount" json:"amount"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	SpentAt   pgtype.Timestamp `db:"spent_at" json:"spent_at"`
}
